# Generated by Django 4.0.4 on 2022-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.TextField(max_length=100)),
                ('Lien', models.TextField(max_length=10)),
                ('Ville', models.TextField(max_length=50)),
                ('Localisation', models.TextField(max_length=100)),
                ('Position', models.TextField(max_length=50)),
                ('Etoile_Avis', models.IntegerField()),
                ('Avis', models.TextField(max_length=10)),
                ('Nbr_Experience', models.TextField(max_length=10)),
                ('Type_Chambre', models.TextField(max_length=100)),
                ('Type_Lit', models.TextField(max_length=50)),
                ('Duree', models.TextField(max_length=10)),
                ('Prix', models.TextField(max_length=10)),
                ('Taxes', models.TextField(max_length=50)),
                ('Periode', models.TextField(max_length=10)),
            ],
        ),
    ]
